<a href="https://colab.research.google.com/github/ashfailham/Python/blob/main/Python_Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python for Data Science from zero to hero.
From the above array, retrieve the values([[3,4],[5,6]]) using indexing.



In [2]:
import numpy as np
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [4,5,6,7,8]

arr1 = np.array([lst1, lst2, lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [6]:
arr1[1:3,1:3]

array([[3, 4],
       [5, 6]])

Retrieving [3,4,5]

In [26]:
arr1[1,1:4]

array([3, 4, 5])